services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
    - "5432"
    ports:
    - "5432:5432"
    command: -p 5432
    volumes: 
      - ./db:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  server:
    restart : always
    build:
      context: .
    ports:
      - 11000:11000
    links:
      - "db:database"
    depends_on:
      "db":
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
