# Generated by Django 4.0 on 2024-05-26 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idb', models.CharField(default='', max_length=120)),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField(default='', max_length=500)),
                ('serial_key', models.TextField(default='', max_length=40)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('bid_view_total', models.IntegerField(default=0)),
                ('bid_view_cur', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('idp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Station', max_length=32)),
                ('content', models.TextField(default='', max_length=500)),
                ('color', models.TextField(default='000000', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_key', models.TextField(default='', max_length=120)),
                ('status', models.BooleanField(default=False)),
                ('idbid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.bid')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
            ],
        ),
    ]
